version: "3"
services:
  backend:
    image: $AWS_ECR_IMAGE
    container_name: backend
    ports:
      - "80:8080"
    environment:
      AWS_RDS_HOSTNAME: $AWS_RDS_HOSTNAME
      AWS_RDS_USERNAME: $AWS_RDS_USERNAME
      AWS_RDS_PASSWORD: $AWS_RDS_PASSWORD
      KAKAO_CLIENT_ID: $KAKAO_CLIENT_ID