version: '3'
services:
  mariadb:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    volumes:
      - ./database/spring-batch-create.sql:/docker-entrypoint-initdb.d/spring-batch-create.sql
      - ./database/service-domain-create.sql:/docker-entrypoint-initdb.d/service-domain-create.sql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul

  redis:
    image: redis:latest
    command: [ "redis-server", "--requirepass", "1234" ]
    hostname: test
    ports:
      - "6379:6379"
