# Springboot configurations
spring.profiles.default: local

spring.datasource:
  url: jdbc:mariadb://localhost:3306/chwihae
  driver-class-name: org.mariadb.jdbc.Driver
  username: root
  password: 1234

spring.data:
  redis:
    url: redis://:1234@localhost:6379

spring.jpa:
  open-in-view: false

spring.batch:
  job.enabled: false
  jdbc.initialize-schema: always

# Custom configurations
kakao:
  client-id: "this is secret value"
  client-secret: "this is secret value"
  oauth2.endpoint: "https://kauth.kakao.com/oauth/token"
  userInfo.endpoint: "https://kapi.kakao.com/v2/user/me"

feign:
  client.config.default:
    connectTimeout: 1000
    readTimeout: 3000
    loggerLevel: HEADERS

jwt:
  secret-key: "tywr1nTbJvWquHdD51gFSEezaYRs1fwAf+mKjxgYosMa"
  token-expired-time-ms: 86400000
---
spring.config.activate.on-profile: local

spring.jpa:
  hibernate:
    ddl-auto: none
  show-sql: true
  properties:
    hibernate:
      format_sql: true