spring.datasource:
  url: ${aws.rds.hostname}
  driver-class-name: org.mariadb.jdbc.Driver
  username: ${aws.rds.username}
  password: ${aws.rds.password}

spring.jpa:
  hibernate:
    ddl-auto: none # do not change

jwt:
  secret-key: ${jwt.secret.key}

kakao:
  client-id: ${kakao.client.id}
  client-secret: ${kakao.client.secret}
